services:
  db:
    image: postgres:15-alpine
    container_name: dino_wallet_db
    restart: always
    environment:
      POSTGRES_USER: manager
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U manager -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: dino_wallet_app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: manager
      DB_PASSWORD: ""
      DB_NAME: wallet_db
      DB_PORT: 5432

volumes:
  postgres_data: